services:
  - type: web
    name: gungun-portfolio-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_KEY
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
